/**
 * Single source of truth for the docs site and the registry generator.
 * Plain data, no imports — `scripts/build-registry.ts` reads this file directly.
 */

export type CatalogGroup = "ui" | "dx" | "agents" | "charts" | "motion";

export type CatalogItem = {
  slug: string;
  title: string;
  description: string;
  group: CatalogGroup;
  /** Base UI component this wraps (for the "Primitive" link). */
  base?: string;
  /** Third-party library it wraps, shown as a link. */
  lib?: { name: string; href: string };
  isNew?: boolean;
  /** Source path under `components/` for multi-file items, e.g. "motion/swap". */
  src?: string;
};

const ui = (slug: string, title: string, description: string, extra: Partial<CatalogItem> = {}): CatalogItem => ({
  slug,
  title,
  description,
  group: "ui",
  ...extra,
});
const dx = (slug: string, title: string, description: string, extra: Partial<CatalogItem> = {}): CatalogItem => ({
  slug,
  title,
  description,
  group: "dx",
  isNew: true,
  ...extra,
});

const kit =
  (group: "agents" | "charts" | "motion") =>
  (slug: string, src: string, title: string, description: string): CatalogItem => ({
    slug,
    title,
    description,
    group,
    src,
    isNew: true,
  });
const ag = kit("agents");
const ch = kit("charts");
const mo = kit("motion");

export const catalog: CatalogItem[] = [
  ui("accordion", "Accordion", "A vertically stacked set of interactive headings that each reveal a section of content.", { base: "accordion" }),
  ui("alert", "Alert", "A callout for important, contextual messages. Six tonal variants mapped to the status palette."),
  ui("alert-dialog", "Alert Dialog", "A modal dialog that interrupts the user with important content and expects a response.", { base: "alert-dialog" }),
  ui("aspect-ratio", "Aspect Ratio", "Displays content within a desired ratio."),
  ui("avatar", "Avatar", "An image element with a fallback for representing the user. Supports stacked groups.", { base: "avatar" }),
  ui("badge", "Badge", "A pill-shaped label for status, counts and metadata."),
  ui("breadcrumb", "Breadcrumb", "Displays the path to the current resource using a hierarchy of links."),
  ui("button", "Button", "Pill-shaped actions with a shared state-layer system. Seven variants, eight sizes.", { base: "button" }),
  ui("button-group", "Button Group", "Groups related buttons together with joined edges."),
  ui("calendar", "Calendar", "A date field component that allows users to enter and edit dates.", {
    lib: { name: "React DayPicker", href: "https://daypicker.dev" },
  }),
  ui("card", "Card", "A tonal container for grouping related content. Outline, tonal and elevated variants."),
  ui("carousel", "Carousel", "A swipeable carousel with motion and keyboard support.", { lib: { name: "Embla", href: "https://www.embla-carousel.com" } }),
  ui("chart", "Chart", "Beautiful charts built on Recharts, themed with the DX data-vis palette.", { lib: { name: "Recharts", href: "https://recharts.org" } }),
  ui("checkbox", "Checkbox", "A control that allows the user to toggle between checked and not checked.", { base: "checkbox" }),
  ui("collapsible", "Collapsible", "An interactive component which expands and collapses a panel.", { base: "collapsible" }),
  ui("combobox", "Combobox", "An input combined with a list of predefined items to select. Supports multiple chips.", { base: "combobox" }),
  ui("command", "Command", "A fast, composable command menu for search and actions.", { lib: { name: "cmdk", href: "https://cmdk.paco.me" } }),
  ui("context-menu", "Context Menu", "A menu that appears on right click or long press.", { base: "context-menu" }),
  ui("data-table", "Data Table", "Sortable, filterable, paginated tables powered by TanStack Table.", {
    lib: { name: "TanStack Table", href: "https://tanstack.com/table" },
  }),
  ui("date-picker", "Date Picker", "A date and range picker composed from Popover and Calendar."),
  ui("dialog", "Dialog", "A window overlaid on the primary content. Spring-scaled, 28px radius.", { base: "dialog" }),
  ui("drawer", "Drawer", "A swipeable panel that slides in from the edge of the screen.", { base: "drawer" }),
  ui("dropdown-menu", "Dropdown Menu", "Displays a menu of actions or options triggered by a button.", { base: "menu" }),
  ui("empty", "Empty", "An empty state with media, title, description and actions."),
  ui("field", "Field", "Label, control, description and error — wired together for accessible forms.", { base: "field" }),
  ui("form", "Form", "A native form element with consolidated error handling.", { base: "form" }),
  ui("hover-card", "Hover Card", "Preview content available behind a link on hover.", { base: "preview-card" }),
  ui("input", "Input", "A text field with a 12px radius and hairline outline.", { base: "input" }),
  ui("input-group", "Input Group", "Add icons, text, buttons and kbd hints inside an input."),
  ui("input-otp", "Input OTP", "Accessible one-time password input with copy-paste support.", { lib: { name: "input-otp", href: "https://input-otp.rodz.dev" } }),
  ui("kbd", "Kbd", "Displays a keyboard key or shortcut."),
  ui("label", "Label", "Renders an accessible label associated with a control."),
  ui("menubar", "Menubar", "A persistent menu common in desktop applications.", { base: "menubar" }),
  ui("meter", "Meter", "A graphical display of a numeric value within a known range.", { base: "meter" }),
  ui("navigation-menu", "Navigation Menu", "A collection of links for navigating websites, with animated popups.", { base: "navigation-menu" }),
  ui("number-field", "Number Field", "A numeric input with steppers and a scrub area.", { base: "number-field" }),
  ui("pagination", "Pagination", "Navigation between pages of content."),
  ui("popover", "Popover", "Displays rich content in a portal, triggered by a button.", { base: "popover" }),
  ui("progress", "Progress", "Displays the status of a task. Supports an indeterminate state.", { base: "progress" }),
  ui("radio-group", "Radio Group", "A set of checkable buttons where only one can be checked at a time.", { base: "radio-group" }),
  ui("resizable", "Resizable", "Accessible resizable panel groups and layouts.", {
    lib: { name: "react-resizable-panels", href: "https://github.com/bvaughn/react-resizable-panels" },
  }),
  ui("scroll-area", "Scroll Area", "A native scroll container with custom, auto-hiding scrollbars.", { base: "scroll-area" }),
  ui("select", "Select", "Displays a list of options for the user to pick from.", { base: "select" }),
  ui("separator", "Separator", "Visually or semantically separates content.", { base: "separator" }),
  ui("sheet", "Sheet", "Extends Dialog to display content that complements the main screen.", { base: "dialog" }),
  ui("sidebar", "Sidebar", "A composable, themeable and collapsible application sidebar."),
  ui("skeleton", "Skeleton", "A shimmering placeholder while content loads."),
  ui("slider", "Slider", "An input where the user selects a value from within a given range.", { base: "slider" }),
  ui("sonner", "Toast", "An opinionated toast component, themed to the DX surface ladder.", { lib: { name: "Sonner", href: "https://sonner.emilkowal.ski" } }),
  ui("spinner", "Spinner", "A twelve-blade activity indicator that inherits currentColor."),
  ui("switch", "Switch", "A control that toggles between on and off.", { base: "switch" }),
  ui("table", "Table", "A responsive table for structured data."),
  ui("tabs", "Tabs", "Layered sections of content with a sliding indicator. Pill and line variants.", { base: "tabs" }),
  ui("textarea", "Textarea", "A multi-line text field."),
  ui("toggle", "Toggle", "A two-state button that can be on or off.", { base: "toggle" }),
  ui("toggle-group", "Toggle Group", "A set of two-state buttons that can be toggled on or off.", { base: "toggle-group" }),
  ui("toolbar", "Toolbar", "A container for grouping a set of controls, with roving focus.", { base: "toolbar" }),
  ui("tooltip", "Tooltip", "A popup that displays information on hover or focus.", { base: "tooltip" }),
  ui("typography", "Typography", "The DX type scale as a single component — display to eyebrow."),

  dx("smooth-input", "Smooth Input", "A text input whose caret glides between characters on a spring."),
  dx("digit-input", "Digit Input", "One-time-code input where each digit rolls in with motion."),
  dx("number-flow", "Number Flow", "Animated number transitions — every digit slides to its new value."),
  dx("autoscale-input", "Autoscale Input", "A giant amount field that shrinks its type to always fit, with locale formatting."),
  dx("expanding-tabs", "Expanding Tabs", "Icon tabs that expand to reveal their label, plus a morphing panel."),
  dx("media-scrubber", "Media Scrubber", "A tactile, spring-driven seek bar for audio and video."),
  dx("glow-border", "Glow Border", "The animated dx-gradient palette border for AI and focus moments."),
  dx("gooey", "Gooey Filter", "SVG gooey and squircle filters for liquid, blob-like UI."),
  dx("animated-icons", "Animated Icons", "Twenty-one micro-interaction icon buttons with morphing motion."),
  dx("stack-scroll", "Stack Scroll", "Scroll-driven stacked steps with per-step progress rails."),
  dx("icon-accordion", "Icon Accordion", "A horizontal accordion where icons expand into cards."),
  dx("text-roll", "Text Roll", "Letters roll vertically on hover, staggered from the edge or the center."),
  dx("text-loop", "Text Loop", "Cycles through words with a blurred vertical slide, plus a useLoop hook."),
  dx("count-up", "Count Up", "Counts to a number when it scrolls into view — tween, scramble or flow."),
  dx("animated-link", "Animated Link", "Underline and fill hover treatments for links, router-ready via render."),
  dx("theme-toggle", "Theme Toggle", "Animated theme icons with View Transition reveals — circle, blur, wipe and more."),
  dx("morph-confirm", "Morph Confirm", "A button that morphs into its own confirmation card."),
  dx("mouse-follow", "Mouse Follow", "A springy custom cursor that follows the pointer within an area."),
  dx("tick-scrollbar", "Tick Scrollbar", "A ruler-style scroll indicator with drag, seek and keyboard control."),
  dx("dev-tools", "Dev Tools", "A breakpoint indicator and live debug panel that only render in development."),
  dx("ai-composer", "AI Composer", "A compound prompt box — rotating placeholders, toggles, model picker and a morphing send/stop button."),
  dx("mention-composer", "Mention Composer", "A prompt box where @mentions become tilted tool cards above the input."),
  dx("chat-thread", "Chat Thread", "An auto-scrolling message log with bubbles and a thinking indicator."),
  dx("text-shimmer", "Text Shimmer", "A light sweep across text for loading and thinking states."),
  dx("mesh-gradient", "Mesh Gradient", "A slow, blurred animated mesh of colour blobs for backgrounds."),
  dx("country-select", "Country Select", "A region picker dialog with flags, search and locale detection."),
  dx("token-swap", "Token Swap", "A swap input with animated digits, max toggle, fiat value and balance errors."),
  dx("wallet-cards", "Wallet Cards", "A grid of cards that expand in place to reveal copy and customise actions."),
  dx("auth-drawer", "Auth Drawer", "A floating sign-in sheet with providers, one-time codes, passkeys and wallets."),
  dx("moving-border", "Moving Border", "A glowing highlight that travels around an element's border."),
  dx("dynamic-island", "Dynamic Island", "A pill that morphs between live states — calls, timers, music and more."),
  dx("color-list", "Color List", "A scroll list where the focused row washes the background in its colour."),
  dx("music-toggle", "Music Toggle", "A play/pause button with animated equaliser bars and optional audio."),
  dx("parallax", "Parallax", "Scroll-linked parallax images and a scale-down reveal."),
  dx("infinite-canvas", "Infinite Canvas", "A pannable grid that wraps forever — drag, scroll or use the arrow keys."),
  dx("feature-explorer", "Feature Explorer", "Product feature pills that expand into descriptions over a crossfading stage."),
  dx("project-showcase", "Project Showcase", "A hover-preview project list that morphs into a detail page."),
  ag("chat-app", "agents/chat-app", "Chat App", "A complete agent chat surface — sidebar, thread, tool calls and a composer, wired together."),
  ag("ai-sidebar", "agents/ai-sidebar", "AI Sidebar", "A collapsible assistant panel that docks beside your app and slides over on small screens."),
  ag("message", "agents/message", "Message", "Composable message parts — header, body, actions and attachments — for assistant and user turns."),
  ag("message-bubble", "agents/message-bubble", "Message Bubble", "Chat bubbles with grouping, avatars and collapsible long messages."),
  ag("message-scroller", "agents/message-scroller", "Message Scroller", "A stick-to-bottom scroll container with a jump-to-latest button for streaming threads."),
  ag("prompt-input", "agents/prompt-input", "Prompt Input", "An auto-growing prompt box with model picker, attachments and a morphing submit button."),
  ag("streaming-response", "agents/streaming-response", "Streaming Response", "Token-by-token text reveal with inline citations and a blinking caret."),
  ag("agent-activity", "agents/agent-activity", "Agent Activity", "A live log of what an agent is doing — steps, searches, tool calls and traces."),
  ag("code-block", "agents/code-block", "Code Block", "A code block with filename, language badge, copy action and line highlights."),
  ag("file-diff", "agents/file-diff", "File Diff", "A unified diff view with added and removed lines, collapsible hunks and stats."),
  ag("tool-result", "agents/tool-result", "Tool Result", "Renders tool calls — terminal output, HTTP requests — with status and timing."),
  ag("tool-approval", "agents/tool-approval", "Tool Approval", "Ask the user before an agent runs a sensitive tool — approve, deny or always allow."),
  ag("approval-card", "agents/approval-card", "Approval Card", "Question and review cards an agent uses to ask for a decision mid-task."),
  ag("todo-list", "agents/todo-list", "Todo List", "An agent plan that checks itself off as steps complete."),
  ag("citations", "agents/citations", "Citations", "Source chips with favicons, a stacked overflow and hover previews."),
  ag("image-generation", "agents/image-generation", "Image Generation", "A progressive reveal for generated images, from noise to final frame."),
  ag("thinking-shimmer", "agents/loading-states/thinking-shimmer", "Thinking Shimmer", "A shimmering “Thinking…” label for the moment before the first token."),
  ag("reasoning-text", "agents/loading-states/reasoning-text", "Reasoning Text", "Rotating reasoning phrases with shimmer, scramble and per-letter variants."),
  ag("agent-progress", "agents/loading-states/agent-progress", "Agent Progress", "A step progress indicator for long-running agent tasks."),
  ch("composition-chart", "charts/composition-chart", "Composition Chart", "Stacked composition over time — hover a band to isolate it."),
  ch("funnel-chart", "charts/funnel-chart", "Funnel Chart", "A smooth conversion funnel with stage drop-off and hover detail."),
  ch("liquidity-heatmap", "charts/liquidity-heatmap", "Liquidity Heatmap", "Price-by-time liquidity density with a crosshair readout."),
  ch("bump-chart", "charts/bump-chart", "Bump Chart", "Rank changes over time, with series that lift on hover."),
  ch("order-book", "charts/order-book", "Order Book", "A live depth ladder — bids, asks, spread and cumulative size."),
  ch("heat-calendar", "charts/heat-calendar", "Heat Calendar", "A contribution-style calendar heatmap with tooltips."),
  ch("returns-calendar", "charts/returns-calendar", "Returns Calendar", "Monthly returns as a diverging calendar grid."),
  ch("price-target-fan", "charts/price-target-fan", "Price Target Fan", "Historical price with a fan of low, mean and high forecasts."),
  mo("motion-button", "motion/button", "Button", "Spring-pressed buttons with stateful, magnetic and metallic variants."),
  mo("motion-input", "motion/input", "Input", "A text field with a floating label and animated validation."),
  mo("motion-select", "motion/select", "Select", "A select whose popup grows out of its trigger."),
  mo("select-morph", "motion/select-morph", "Select Morph", "A select that morphs its trigger into the option list."),
  mo("motion-combobox", "motion/combobox", "Combobox", "A searchable select with a sliding highlight."),
  mo("multi-select", "motion/multi-select", "Multi Select", "Pick many options; chips spring in and out of the trigger."),
  mo("motion-checkbox", "motion/checkbox", "Checkbox", "A checkbox with a drawn tick and squash on press."),
  mo("radio", "motion/radio", "Radio", "Radio options with a dot that glides between choices."),
  mo("motion-switch", "motion/switch", "Switch", "A switch with a stretchy thumb."),
  mo("motion-tabs", "motion/tabs", "Tabs", "Scrollable tabs with a shared-layout indicator."),
  mo("otp-input", "motion/otp-input", "OTP Input", "One-time-code slots with a travelling caret and success state."),
  mo("range-slider", "motion/range-slider", "Range Slider", "A spring-smoothed slider with step ticks."),
  mo("range-slider-inline", "motion/range-slider-inline", "Inline Slider", "A compact slider with its label and value inside the track."),
  mo("range-slider-fluid", "motion/range-slider-fluid", "Fluid Slider", "A slider whose fill swells as you drag."),
  mo("range-slider-wave", "motion/range-slider-wave", "Wave Slider", "An equaliser-style slider of animated bars."),
  mo("range-slider-bubble", "motion/range-slider-bubble", "Bubble Slider", "A slider with a value bubble that pops up on drag."),
  mo("range-slider-ruler", "motion/range-slider-ruler", "Ruler Slider", "A draggable ruler with momentum and detents."),
  mo("wheel-picker", "motion/wheel-picker", "Wheel Picker", "An iOS-style 3D wheel picker with ticks and inertia."),
  mo("date-range-picker", "motion/date-range-picker", "Date Range Picker", "A calendar range picker with presets and animated months."),
  mo("color-selector", "motion/color-selector", "Color Selector", "A swatch picker that expands into a palette."),
  mo("adaptive-stepper", "motion/adaptive-stepper", "Adaptive Stepper", "A numeric stepper whose controls adapt to the value."),
  mo("expandable-control", "motion/expandable-control", "Expandable Control", "A compact control that expands into a full adjuster."),
  mo("signup-form", "motion/signup-form", "Signup Form", "A multi-step sign-up form with morphing transitions."),
  mo("action-swap", "motion/action-swap", "Action Swap", "Swap a button's icon and label with a slide."),
  mo("action-swap-blur", "motion/action-swap-blur", "Action Swap Blur", "Swap a button's content through a blur."),
  mo("action-swap-roll", "motion/action-swap-roll", "Action Swap Roll", "Roll a button's label to the next state."),
  mo("action-swap-cascade", "motion/action-swap-cascade", "Action Swap Cascade", "Letters cascade into the next label."),
  mo("expanding-arrow-button", "motion/expanding-arrow-button", "Expanding Arrow Button", "A button whose arrow stretches on hover."),
  mo("hold-action-button", "motion/hold-action-button", "Hold Action Button", "Press and hold to confirm a destructive action."),
  mo("slide-action-button", "motion/slide-action-button", "Slide Action Button", "Slide to confirm, with snap-back and success states."),
  mo("expandable-action-bar", "motion/expandable-action-bar", "Expandable Action Bar", "A floating bar that expands into a set of actions."),
  mo("overflow-actions", "motion/overflow-actions", "Overflow Actions", "Actions that collapse into a morphing overflow menu."),
  mo("bloom-menu", "motion/bloom-menu", "Bloom Menu", "A button that blooms into a radial menu."),
  mo("motion-theme-toggle", "motion/theme-toggle", "Transition Toggle", "A sun–moon toggle with rect, circle, blur and blinds View Transitions."),
  mo("motion-popover", "motion/popover", "Popover", "A hover or click popover that springs from its anchor."),
  mo("popover-morph", "motion/popover-morph", "Popover Morph", "A trigger that morphs into its popover."),
  mo("motion-tooltip", "motion/tooltip", "Tooltip", "Tooltips that glide between anchors and can follow the cursor."),
  mo("motion-context-menu", "motion/context-menu", "Context Menu", "A right-click and long-press menu with spring entrance."),
  mo("motion-drawer", "motion/drawer", "Drawer", "A draggable drawer with snap points."),
  mo("bottom-sheet", "motion/bottom-sheet", "Bottom Sheet", "A mobile bottom sheet with drag-to-dismiss."),
  mo("morphing-modal", "motion/morphing-modal", "Morphing Modal", "A card that morphs into a full modal."),
  mo("center-morph-modal", "motion/center-morph-modal", "Center Morph Modal", "A trigger that morphs into a centered dialog."),
  mo("morphing-lightbox", "motion/morphing-lightbox", "Morphing Lightbox", "Thumbnails that morph into a full-screen viewer."),
  mo("command-palette", "motion/command-palette", "Command Palette", "A ⌘K palette with grouped results and a sliding cursor."),
  mo("morphing-search", "motion/morphing-search", "Morphing Search", "A search button that morphs into a results panel."),
  mo("feedback-widget", "motion/feedback-widget", "Feedback Widget", "A floating feedback button that morphs into a form."),
  mo("notification-stack", "motion/notification-stack", "Notification Stack", "Stacked notifications that fan out on hover."),
  mo("animated-toast-stack", "motion/animated-toast-stack", "Toast Stack", "Stacked toasts with swipe-to-dismiss."),
  mo("motion-dynamic-island", "motion/dynamic-island", "Live Activity Island", "A pill that morphs between live activities."),
  mo("motion-breadcrumb", "motion/breadcrumb", "Breadcrumb", "Breadcrumbs that collapse and expand with motion."),
  mo("animated-sidebar", "motion/animated-sidebar", "Animated Sidebar", "A collapsible app sidebar with nested sections and springs."),
  mo("bounce-sidebar", "motion/bounce-sidebar", "Bounce Sidebar", "A section rail with a bouncy active indicator."),
  mo("dock", "motion/dock", "Dock", "A macOS-style dock with magnification."),
  mo("expandable-tabs", "motion/expandable-tabs", "Expandable Tabs", "Icon tabs that expand to show labels."),
  mo("morphing-tabs", "motion/morphing-tabs", "Morphing Tabs", "Tabs whose panel morphs between sizes."),
  mo("shared-layout-bg", "motion/shared-layout-bg", "Shared Layout Background", "A hover highlight that glides between items."),
  mo("file-tree", "motion/file-tree", "File Tree", "A collapsible file tree with animated folders."),
  mo("preview-rail", "motion/preview-rail", "Preview Rail", "A link rail that previews each destination on hover."),
  mo("bouncy-accordion", "motion/bouncy-accordion", "Bouncy Accordion", "An accordion with springy open and close."),
  mo("pull-to-refresh", "motion/pull-to-refresh", "Pull To Refresh", "Pull down to refresh with a rubber-band spinner."),
  mo("swipeable-list", "motion/swipeable-list", "Swipeable List", "List rows with swipe actions."),
  mo("sortable-list", "motion/sortable-list", "Sortable List", "Drag to reorder with spring layout."),
  mo("motion-table", "motion/table", "Table", "Sort, resize, reorder, select and edit — a motion data table."),
  mo("card-folder", "motion/card-folder", "Card Folder", "Cards that fan out of a folder."),
  mo("project-folder", "motion/project-folder", "Project Folder", "A folder that opens to reveal project files."),
  mo("tilt-card", "motion/tilt-card", "Tilt Card", "A card that tilts toward the pointer."),
  mo("wallet-card", "motion/wallet-card", "Wallet Card", "A crypto wallet card with account switcher and balances."),
  mo("swap", "motion/swap", "Swap", "A token swap widget with quotes and a token picker."),
  mo("prediction-market", "motion/prediction-market", "Prediction Market", "A market detail view with outcome odds and a trade panel."),
  mo("prediction-market-card", "motion/prediction-market-card", "Prediction Market Card", "A compact market card with yes/no odds."),
  mo("availability-scheduler", "motion/availability-scheduler", "Availability Scheduler", "Weekly hours with copy-to-days and time selects."),
  mo("file-upload", "motion/file-upload", "File Upload", "A drop zone with per-file progress."),
  mo("attachment-upload", "motion/attachment-upload", "Attachment Upload", "Attachment chips with upload progress and previews."),
  mo("knockout-bracket", "motion/knockout-bracket", "Knockout Bracket", "A tournament bracket with hover paths."),
  mo("knockout-wheel", "motion/knockout-wheel", "Knockout Wheel", "A radial tournament bracket."),
  mo("infinite-masonry", "motion/infinite-masonry", "Infinite Masonry", "A virtualised masonry grid that loads forever."),
  mo("cylinder-carousel", "motion/cylinder-carousel", "Cylinder Carousel", "A 3D cylinder carousel with drag and inertia."),
  mo("marquee", "motion/marquee", "Marquee", "An infinite marquee that pauses on hover."),
  mo("not-found", "motion/not-found", "Not Found", "Five animated 404 pages — glitch, magnetic, spotlight, stacked and terminal."),
  mo("text-reveal", "motion/text-reveal", "Text Reveal", "Words blur and rise into place."),
  mo("text-cascade", "motion/text-cascade", "Text Cascade", "Letters cascade in on a stagger."),
  mo("text-scramble", "motion/text-scramble", "Text Scramble", "Text that scrambles through glyphs before settling."),
  mo("motion-text-shimmer", "motion/text-shimmer", "Shimmer Text", "A light sweep across text."),
  mo("chromatic-text-reveal", "motion/chromatic-text-reveal", "Chromatic Text Reveal", "Text revealed through RGB-split colour fringes."),
  mo("animated-number", "motion/animated-number", "Animated Number", "Numbers that spring between values."),
  mo("number-ticker", "motion/number-ticker", "Number Ticker", "Rolling digit columns for counters and prices."),
  mo("digit-swap", "motion/digit-swap", "Digit Swap", "Digits swap with a vertical slide."),
  mo("animated-badge", "motion/animated-badge", "Animated Badge", "Badges that morph between states."),
  mo("loader", "motion/loader", "Loader", "A set of small, calm loading indicators."),
  mo("smooth-scroll", "motion/smooth-scroll", "Smooth Scroll", "Inertial wheel scrolling with shared scroll motion values."),
  mo("scroll-progress", "motion/scroll-progress", "Scroll Progress", "A reading progress bar."),
  mo("scroll-reveal", "motion/scroll-reveal", "Scroll Reveal", "Reveal content as it scrolls into view."),
  mo("scroll-to", "motion/scroll-to", "Scroll To", "Smooth anchor scrolling with offsets."),
  mo("motion-parallax", "motion/parallax", "Parallax Layers", "Scroll-linked parallax layers."),
  mo("shader-background", "motion/shader-background", "Shader Background", "An animated WebGL gradient background."),
];

export const groupLabels: Record<CatalogGroup, string> = {
  ui: "Components",
  dx: "DX Motion",
  agents: "Agents",
  charts: "Charts",
  motion: "Motion Kit",
};

export const catalogBySlug = Object.fromEntries(catalog.map((c) => [c.slug, c])) as Record<string, CatalogItem>;

export type GuidePage = { slug: string; title: string; description: string };

export const guides: GuidePage[] = [
  { slug: "introduction", title: "Introduction", description: "Accessible, motion-first components you copy into your app and own." },
  { slug: "installation", title: "Installation", description: "Add DX UI to a new or existing React + Tailwind 4 project." },
  { slug: "cli", title: "CLI", description: "Use the dx-ui CLI, or the shadcn CLI, to add components from the registry." },
  { slug: "theming", title: "Theming", description: "CSS variables, the tonal surface ladder, and the DX Gradient accent." },
  { slug: "tokens", title: "Tokens", description: "Every color, radius, motion and state-layer token in the system." },
  { slug: "typography", title: "Typography", description: "Google Sans Flex and Google Sans Code, on a tight fluid scale." },
  { slug: "motion", title: "Motion", description: "Springs with no bounce. The rules behind every animation in DX UI." },
  { slug: "dark-mode", title: "Dark mode", description: "Class-based dark mode with a no-flash theme script." },
];

export type BlockItem = { slug: string; title: string; description: string; height: number };

export const blocks: BlockItem[] = [
  { slug: "dashboard-01", title: "Dashboard", description: "Collapsible sidebar, animated KPI cards, interactive charts and a data table.", height: 900 },
  { slug: "login-01", title: "Login — split screen", description: "Split-screen sign in with social providers and a brand panel.", height: 760 },
  { slug: "signup-01", title: "Sign up", description: "Account creation with field validation and a password meter.", height: 760 },
  { slug: "otp-01", title: "Verify code", description: "One-time code verification with the animated Digit Input.", height: 640 },
  { slug: "forgot-01", title: "Forgot password", description: "Request a reset link, with a success state.", height: 600 },
  { slug: "settings-01", title: "Settings", description: "Profile, account, notifications, billing and team in one layout.", height: 960 },
];
